server:
  applicationConnectors:
    - type: http
      port: ${BR_SERVER_PORT:-8080}

externalBaseUrl: ${BR_EXTERNAL_BASE_URL:-http://localhost:8080}

iiifUrl: https://images.diginfra.net/api/pim

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR