server:
  applicationConnectors:
    - type: http
      port: ${BR_SERVER_PORT:-8080}

externalBaseUrl: ${BR_EXTERNAL_BASE_URL:-http://localhost:8080}

pageSize: ${AR_PAGE_SIZE:-100}

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR